#!/bin/sh
export BEET_WORKDIR=$(mktemp -d)
find -name *.cue -exec sh -xec '
WAVE_BASEDIR="$(dirname "{}")"
WAVE="${WAVE_BASEDIR}/$(grep FILE "{}" | sed -e "s/^FILE \"//" -e "s/\" WAVE\s$//")"
mkdir -p "${BEET_WORKDIR}/${WAVE_BASEDIR}"
shnsplit -d "${BEET_WORKDIR}/${WAVE_BASEDIR}" -f "{}" -o flac -a "${WAVE}" -- "${WAVE}"
' \;
beet import --from-scratch "${BEET_WORKDIR}"
rm -rf "${BEET_WORKDIR}"