name: build and push

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: build beets-shntool
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./images/beets-shntool
          push: true
          tags: ghcr.io/fancl20/beets-shntool:latest
      - name: build coding-workspace
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./images/coding-workspace
          push: true
          tags: ghcr.io/fancl20/coding-workspace:latest
      - name: build roon-server
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./images/roon-server
          push: true
          tags: ghcr.io/fancl20/roon-server:latest
