name: Build and Push

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Build beets-shntool
        uses: docker/build-push-action@v4
        with:
          context: ./images/beets-shntool
          push: true
          tags: ghcr.io/fancl20/beets-shntool:latest
      - name: Build clash
        uses: docker/build-push-action@v4
        with:
          context: ./images/clash
          push: true
          tags: ghcr.io/fancl20/clash:latest
      - name: Build coding-workspace
        uses: docker/build-push-action@v4
        with:
          context: ./images/coding-workspace
          push: true
          tags: ghcr.io/fancl20/coding-workspace:latest
      - name: Build fava
        uses: docker/build-push-action@v4
        with:
          context: ./images/fava
          push: true
          tags: ghcr.io/fancl20/fava:latest
      - name: Build roon-server
        uses: docker/build-push-action@v4
        with:
          context: ./images/roon-server
          push: true
          tags: ghcr.io/fancl20/roon-server:latest
